title: Nate Carlson # your name (or website title) here
logo: "/images/profile_image.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  <a href="pdf/NCarlson-Resume-Fall2021.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/natbcar/">LinkedIn</a> |
  <a href="https://github.com/chriskhanhtran">GitHub</a>
  </p>
  I am a senior in the <a href="https://acme.byu.edu/">Applied and Computational Mathematics (ACME)</a> program at BYU.
  <br><br>
  This summer I will be joining CVS Health as a Data Science Intern on the Health Analytics & Behavior Change Team.
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
